language: php

php:
    - 7.2
    - 7.3
    - 7.4

dist: bionic
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - travis_retry composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpcs --standard=psr2 src
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - |
        if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
